---
driver_plugin: vagrant

platforms:
- name: centos-6.4
  driver_config:
    box: opscode-centos-6.4
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_centos-6.4_provisionerless.box
    require_chef_omnibus: true
    customize:
      vrde: '"on"'
      vrdeport: '"5000-5010"'
      vrdeauthtype: '"null"'

suites:
- name: default
  run_list: ["recipe[gitorious]"]
  attributes: {}
